import crypto from 'crypto';
import type { Request, Response } from 'express';
import pg from 'pg';
const { Client } = pg;

type Provider = 'metricool' | 'openai' | 'groq' | 'gemini';
const SUPPORTED_PROVIDERS = new Set<Provider>(['metricool', 'openai', 'groq', 'gemini']);
const PROVIDER_ENDPOINTS: Record<Provider, string> = { metricool:'https://app.metricool.com', openai:'https://api.openai.com', groq:'https://api.groq.com', gemini:'https://generativelanguage.googleapis.com' };
function db(){const url=process.env.DATABASE_URL;if(!url)throw Object.assign(new Error('DATABASE_URL is not configured'),{statusCode:503});return new Client({connectionString:url,ssl:{rejectUnauthorized:false}})}
function key(){const raw=process.env.AI_CREDENTIAL_MASTER_KEY||process.env.THIRD_PARTY_CREDENTIAL_MASTER_KEY;if(!raw)throw Object.assign(new Error('Third-party credential encryption key is not configured'),{statusCode:503});if(/^[0-9a-fA-F]{64}$/.test(raw))return Buffer.from(raw,'hex');const k=Buffer.from(raw,'base64');if(k.length!==32)throw Object.assign(new Error('Third-party credential encryption key must decode to exactly 32 bytes'),{statusCode:503});return k}
function enc(s:string){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([c.update(s,'utf8'),c.final()]);return{encrypted:data.toString('base64'),iv:iv.toString('base64'),authTag:c.getAuthTag().toString('base64')}}
function dec(e:string,i:string,t:string){const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64'));d.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([d.update(Buffer.from(e,'base64')),d.final()]).toString('utf8')}
function admin(req:Request){const u=(req as any).user;if(!u?.id)throw Object.assign(new Error('Authenticated user is required'),{statusCode:401});if(!['owner','admin'].includes(String(u.role||'').toLowerCase()))throw Object.assign(new Error('Owner or admin access is required'),{statusCode:403});return u}
function provider(v:unknown):Provider{const p=String(v||'').trim().toLowerCase() as Provider;if(!SUPPORTED_PROVIDERS.has(p))throw Object.assign(new Error('Provider is not supported yet'),{statusCode:400});return p}
function mask(s:string){return s.length<=8?'••••••••':`${s.slice(0,4)}••••${s.slice(-4)}`}
async function audit(req:Request,action:string,id:string|null,metadata:Record<string,unknown>){const u=(req as any).user;if(!u?.id)return;const c=db();await c.connect();try{await c.query(`insert into public.zoal_activity_logs (id,user_id,email,action,timestamp,ip,user_agent,resource_type,resource_id,metadata,result,severity,source) values ($1,$2,$3,$4,now(),$5,$6,'third_party_integration',$7,$8::jsonb,'success','info','admin')`,[crypto.randomUUID(),u.id,u.email||null,action,req.ip||'',req.headers['user-agent']||'',id,JSON.stringify(metadata)])}finally{await c.end()}}
function metricool(s:string){try{const x=JSON.parse(s),userToken=String(x?.userToken??x?.token??'').trim(),userId=String(x?.userId??'').trim(),blogId=String(x?.blogId??'').trim();return userToken&&userId&&blogId?{userToken,userId,blogId}:null}catch{return null}}
async function verify(p:Provider,s:string){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),10000);try{let url='';const h:Record<string,string>={Accept:'application/json'};if(p==='metricool'){const c=metricool(s);if(!c)return{ok:false,status:400,message:'Metricool credential must contain userToken, userId and blogId'};const u=new URL('https://app.metricool.com/api/admin/simpleProfiles');u.searchParams.set('blogId',c.blogId);u.searchParams.set('userId',c.userId);url=u.toString();h['X-Mc-Auth']=c.userToken}else if(p==='openai'){url='https://api.openai.com/v1/models';h.Authorization=`Bearer ${s.trim()}`}else if(p==='groq'){url='https://api.groq.com/openai/v1/models';h.Authorization=`Bearer ${s.trim()}`}else{url='https://generativelanguage.googleapis.com/v1beta/models';h['x-goog-api-key']=s.trim()}const r=await fetch(url,{method:'GET',headers:h,signal:ac.signal});if(!r.ok)return{ok:false,status:r.status,message:`${p} API verification failed with HTTP ${r.status}`};return{ok:true,status:r.status,message:`${p} API connectivity verified successfully.`}}catch(e:any){return{ok:false,status:e?.name==='AbortError'?504:502,message:e?.name==='AbortError'?`${p} API verification timed out`:e?.message||`${p} API verification failed`}}finally{clearTimeout(timer)}}
export async function listThirdPartyIntegrations(req:Request,res:Response){try{admin(req);const c=db();await c.connect();try{const r=await c.query(`select id,provider,display_name,category,auth_type,status,last_error,created_at,updated_at,last_verified_at,rotated_at from public.zoal_third_party_integrations order by display_name asc`);return res.json({ok:true,integrations:r.rows.map((x:any)=>({...x,secretConfigured:true}))})}finally{await c.end()}}catch(e:any){return res.status(e?.statusCode||500).json({ok:false,error:e?.message||'Failed to load integrations'})}}
export async function createThirdPartyIntegration(req:Request,res:Response){try{const u=admin(req),p=provider(req.body?.provider),displayName=String(req.body?.displayName||'').trim(),secret=String(req.body?.secret||''),category=String(req.body?.category||'Other').trim().slice(0,80)||'Other';if(!displayName||displayName.length>120)return res.status(400).json({ok:false,error:'A valid display name is required'});if(secret.length<8||secret.length>4096)return res.status(400).json({ok:false,error:'Credential length is invalid'});const e=enc(secret),c=db();await c.connect();try{const r=await c.query(`insert into public.zoal_third_party_integrations (provider,display_name,category,endpoint,auth_type,credential_name,encrypted_secret,iv,auth_tag,status,created_by,updated_by,rotated_at) values ($1,$2,$3,$4,'api_key','primary',$5,$6,$7,'inactive',$8,$8,now()) returning id,provider,display_name,category,auth_type,status,created_at,updated_at,last_verified_at,rotated_at`,[p,displayName,category,PROVIDER_ENDPOINTS[p],e.encrypted,e.iv,e.authTag,String(u.id)]);const row=r.rows[0];await audit(req,'THIRD_PARTY_INTEGRATION_CREATE',row.id,{provider:p});return res.status(201).json({ok:true,integration:{...row,secretConfigured:true,secretMasked:mask(secret)}})}finally{await c.end()}}catch(e:any){return res.status(e?.code==='23505'?409:e?.statusCode||500).json({ok:false,error:e?.code==='23505'?'This provider credential already exists':e?.message||'Failed to save integration'})}}
export async function updateThirdPartyIntegration(req:Request,res:Response){try{const u=admin(req),id=String(req.params.id||'').trim(),displayName=req.body?.displayName===undefined?undefined:String(req.body.displayName).trim(),category=req.body?.category===undefined?undefined:String(req.body.category).trim().slice(0,80),status=req.body?.status===undefined?undefined:String(req.body.status).toLowerCase(),secret=req.body?.secret===undefined?undefined:String(req.body.secret);if(status!==undefined&&!['active','inactive','error'].includes(status))return res.status(400).json({ok:false,error:'Invalid integration status'});if(secret!==undefined&&(secret.length<8||secret.length>4096))return res.status(400).json({ok:false,error:'Credential length is invalid'});const c=db();await c.connect();try{if(status==='active'){const q=await c.query(`select last_verified_at from public.zoal_third_party_integrations where id=$1`,[id]);if(!q.rows[0]?.last_verified_at)return res.status(409).json({ok:false,error:'Integration must pass live provider verification before activation'})}const sets=['updated_by=$2'],vals:any[]=[id,String(u.id)];if(displayName!==undefined){sets.push(`display_name=$${vals.length+1}`);vals.push(displayName)}if(category!==undefined){sets.push(`category=$${vals.length+1}`);vals.push(category||'Other')}if(status!==undefined){sets.push(`status=$${vals.length+1}`);vals.push(status)}if(secret!==undefined){const e=enc(secret);sets.push(`encrypted_secret=$${vals.length+1}`,`iv=$${vals.length+2}`,`auth_tag=$${vals.length+3}`,'rotated_at=now()','last_verified_at=null','last_error=null');vals.push(e.encrypted,e.iv,e.authTag);if(status===undefined){sets.push(`status=$${vals.length+1}`);vals.push('inactive')}}vals.push(id);const r=await c.query(`update public.zoal_third_party_integrations set ${sets.join(',')} where id=$${vals.length} returning id,provider,display_name,category,auth_type,status,created_at,updated_at,last_verified_at,rotated_at`,vals);if(!r.rows[0])return res.status(404).json({ok:false,error:'Integration not found'});await audit(req,'THIRD_PARTY_INTEGRATION_UPDATE',id,{credentialRotated:secret!==undefined,statusChanged:status!==undefined});return res.json({ok:true,integration:{...r.rows[0],secretConfigured:true}})}finally{await c.end()}}catch(e:any){return res.status(e?.statusCode||500).json({ok:false,error:e?.message||'Failed to update integration'})}}
export async function deleteThirdPartyIntegration(req:Request,res:Response){try{admin(req);const id=String(req.params.id||'').trim(),c=db();await c.connect();try{const r=await c.query(`delete from public.zoal_third_party_integrations where id=$1 returning id,provider`,[id]);if(!r.rows[0])return res.status(404).json({ok:false,error:'Integration not found'});await audit(req,'THIRD_PARTY_INTEGRATION_DELETE',id,{provider:r.rows[0].provider});return res.json({ok:true})}finally{await c.end()}}catch(e:any){return res.status(e?.statusCode||500).json({ok:false,error:e?.message||'Failed to delete integration'})}}
export async function testThirdPartyIntegration(req:Request,res:Response){try{admin(req);const id=String(req.params.id||'').trim(),c=db();await c.connect();try{const q=await c.query(`select id,provider,encrypted_secret,iv,auth_tag from public.zoal_third_party_integrations where id=$1`,[id]);const row=q.rows[0];if(!row)return res.status(404).json({ok:false,error:'Integration not found'});const p=provider(row.provider),result=await verify(p,dec(row.encrypted_secret,row.iv,row.auth_tag));if(!result.ok){await c.query(`update public.zoal_third_party_integrations set status='error',last_verified_at=null,last_error=$2,updated_at=now() where id=$1`,[id,result.message]);await audit(req,'THIRD_PARTY_INTEGRATION_TEST',id,{provider:p,apiCalled:true,verified:false,httpStatus:result.status});return res.status(result.status>=500?502:400).json({ok:false,verified:false,active:false,error:result.message})}await c.query(`update public.zoal_third_party_integrations set status='active',last_verified_at=now(),last_error=null,updated_at=now(),updated_by=$2 where id=$1`,[id,String((req as any).user.id)]);await audit(req,'THIRD_PARTY_INTEGRATION_TEST',id,{provider:p,apiCalled:true,verified:true,httpStatus:result.status});return res.json({ok:true,verified:true,active:true,message:result.message})}finally{await c.end()}}catch(e:any){return res.status(e?.statusCode||502).json({ok:false,verified:false,active:false,error:e?.message||'Integration test failed'})}}
